FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Student Information
This API manipulates the students information of College.

## Students Collection [/students]

    
### Get Students list [GET]
This operation retrieves the list of all students
+ Response 200 (application/json)

        [
            {
                "ID" : 1,
                "Name" : "Vivek Baraskar"
            },
            {
                "ID" : 2,
                "Name" : "Chetan Baraskar"
            },
            {
                "ID" : 3,
                "Name" : "Kishor Baraskar"
            },
            {
                "ID" : 4,
                "Name" : "Kiran Baraskar"
            }
        ]  

### Add Student [POST]    
This operation can be used to add a new student record.
+ Request (application/json)
        
        {
            "ID": 5,
            "Name" : "Sameer Baraskar"
        }
        
+ Response 201 (application/json)
        
        {
            "Status" : "Student added successfully."
        }


        
+ Response 400 (application/json)
        
        {
            "Status" : "Bad Request"
        }